{% set name = "smqtk-descriptors" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smqtk_descriptors-{{ version }}.tar.gz
  sha256: ec0c6ce48dd06b59795b44424957f92c9d5adb0765f28b11513dcf5622214797

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1.19.5
    - smqtk-core >=0.20.0
    - smqtk-dataprovider >=0.19.0
    - smqtk-image-io >=0.18.0

test:
  imports:
    - smqtk_descriptors
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kitware/SMQTK-Descriptors
  summary: Algorithms, data structures and utilities around computing descriptor vectors from data.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - barry-ravichandran
